### ISSUE TITLE
database connection

### ISSUE THREAD

**Issue by Arunagiri666** [Bhanu1776/Freelansters#23]
i have connected the backend with this code. when i try to login .The details is not updated in database and not working.What to do?

**Comment by Bhanu1776** [comment]
Have you ensured that the environment variables are set up correctly?

**Comment by Arunagiri666** [comment]
yes ,and  I have attached a screenshot
![Screenshot 2024-09-17 215636](https://github.com/user-attachments/assets/e6b9117b-fd3c-4471-8f17-2b9cc83a1be5)
